services:
  eureka-service:
    image: boboyevsardor/eureka-service1
    ports:
      - "8761:8761"


  gateway-service:
    image: boboyevsardor/gateway-service1
    ports:
      - "8080:8080"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
    depends_on:
      - eureka-service


  auth-service:
    image: boboyevsardor/auth-service1
    ports:
      - "8089:8089"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 2004
    depends_on:
      - eureka-service
      - db




  contact-service:
    image: boboyevsardor/contact-service1
    ports:
      - "8095:8095"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 2004
    depends_on:
      - eureka-service
      - db

  chat-service:
    image: boboyevsardor/chat-service1
    ports:
      - "8099:8099"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 2004
    depends_on:
      - eureka-service
      - db


  message-service:
    image: boboyevsardor/message-service1
    ports:
      - "8084:8084"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 2004
    depends_on:
      - eureka-service
      - db

  story-service:
    image: boboyevsardor/story-service1
    ports:
      - "8096:8096"
    environment:
      EUREKA_URI: http://eureka-service:8761/eureka/
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 2004
    depends_on:
      - eureka-service
      - db


  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2004
      POSTGRES_DB: sardor
    volumes:
      - ./db-data:/var/lib/postgresql/data